# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            artelowcost/artinpocket
tagline:          Un blog d'artinpocket
description:      artelowcost bloc d'<a href="http://www.artinpocket.cat" target="_blank">artinpocket</a>. Creat per <a href="http://www.oxygen.cat/" target="_blank">Oxygen.cat</a>.
url:              'http://www.artelowcost.com'

author:
  name:           'Ramon Gil'
  url:            https://twitter.com/freecates

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/artelowcost/artelowcost.github.io

assets: 
  baseurl: /public/
